services:
  api1: &api
    image: rinha-fraud-2026-kotlin:latest
    build: .
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    healthcheck:
      test: ["CMD-SHELL", "test -S $$SOCK"]
      interval: 2s
      timeout: 1s
      retries: 90
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

  api2:
    <<: *api
    build: !reset null
    image: rinha-fraud-2026-kotlin:latest
    environment:
      - SOCK=/run/sock/api2.sock

  lb:
    image: rinha-fraud-2026-kotlin:latest
    build: !reset null
    entrypoint:
      - java
      - --add-opens
      - java.base/sun.nio.ch=ALL-UNNAMED
      - --add-opens
      - java.base/java.nio=ALL-UNNAMED
      - -Xms16m
      - -Xmx24m
      - -XX:+UseG1GC
      - -XX:MaxMetaspaceSize=16m
      - -XX:ReservedCodeCacheSize=8m
      - -Dio.netty.maxDirectMemory=4194304
      - -cp
      - /app.jar
      - rinhakotlin.LoadBalancerKt
    restart: always
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    environment:
      - UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
      - PORT=9999
      - WORKERS=1
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

volumes:
  sock:
